version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/dev
    ports:
      - '80:80'
      - '2000:2000'
    volumes:
      - /:/etc/ssl
      - /:/etc/letsencrypt
      - /:/data/letsencrypt
      - /:/var/log/nginx
