version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null # --quiet

  ie-marketing:
    image: 'magrelo/ie-marketing:latest'
    container_name: ie-marketing
    restart: on-failure

  position-paper:
    image: 'magrelo/position-paper:latest'
    container_name: position-paper
    restart: on-failure
    environment:
      - NODE_ENV=production
      - MONGODB_URL_INT=mongodb://mongodb/position-dev
      - MAGIC_SECRET_KEY=${MAGIC_SECRET_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - STREAM_API_KEY=${STREAM_API_KEY}
      - STREAM_API_SECRET=${STREAM_API_SECRET}

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
