version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_PORT=${MONGO_PORT}

      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}

      - APP_MONGO_HOST=${MONGO_HOST}
      - APP_MONGO_DB=${APP_MONGO_DB}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}

    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
      - ./mongo/createUsers.sh:/docker-entrypoint-initdb.d/createUsers.sh:ro
    command: mongod

  ie-marketing:
    image: 'magrelo/ie-marketing:latest'
    container_name: ie-marketing
    restart: on-failure

  position-paper:
    image: 'magrelo/position-paper:latest'
    container_name: position-paper
    restart: on-failure
    environment:
      - NODE_ENV=production
      - MONGODB_URL_INT=mongodb://${APP_MONGO_USER}:${APP_MONGO_PASS}@mongodb:27017/${APP_MONGO_DB}
      - MAGIC_SECRET_KEY=${MAGIC_SECRET_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - STREAM_API_KEY=${STREAM_API_KEY}
      - STREAM_API_SECRET=${STREAM_API_SECRET}

  clubstack:
    image: 'magrelo/reading-project:latest'
    container_name: clubstack
    restart: on-failure
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGODB_URL_INT=mongodb://${APP_MONGO_USER}:${APP_MONGO_PASS}@mongodb:27017/clubstack
      - MAGIC_SECRET_KEY=${MAGIC_SECRET_KEY}
      - STREAM_API_KEY=${STREAM_API_KEY}
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - STRIPE_TEST_KEY=${STRIPE_TEST_KEY}
      - STRIPE_SUBSCRIBE_SECRET=${STRIPE_SUBSCRIBE_SECRET}

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
