version: '3'
services:
  homepage:
    image: 'magrelo/servesa-home:latest'
    container_name: homepage
    restart: on-failure

  logstash:
    build: ./logstash
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.5-alpine
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
