version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null # --quiet

  ie-marketing:
    image: 'magrelo/ie-marketing:latest'
    container_name: ie-marketing
    restart: on-failure

  # loadbalancer
  nginx:
    container_name: nginx
    build:
      context: ./nginx/prod
    ports:
      - '80:80'
      - '443:443'
      - '5601:5601'
      - '9200:9200'
    volumes:
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt
